const Temple = [
  {
    id: 1,
    img: "./../checkoutform/images/pagi_2.png",
    name: "Swaminarayan temple, Bhuj",
    location: "Bhuj, Gujarat, India",
    review: "2 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 2,
    img: "./../checkoutform/images/pagi_2.png",
    name: "BAPS Swaminarayan Temple, Jamnagar",
    location: "Bhuj, Gujarat, India",
    review: "1 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 3,
    img: "./../checkoutform/images/pagi_2.png",
    name: "Swaminarayan Akshardham Gujarat",
    location: "Bhuj, Gujarat, India",
    review: "2 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 4,
    img: "./../checkoutform/images/pagi_2.png",
    name: "Swaminarayan temple, Bhuj",
    location: "Bhuj, Gujarat, India",
    review: "3 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 5,
    img: "./../checkoutform/images/pagi_2.png",
    name: "BAPS Swaminarayan Temple, Jamnagar",
    location: "Bhuj, Gujarat, India",
    review: "5 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 6,
    img: "./../checkoutform/images/pagi_2.png",
    name: "Swaminarayan Akshardham Gujarat",
    location: "Bhuj, Gujarat, India",
    review: "3 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 7,
    img: "./../checkoutform/images/pagi_2.png",
    name: "Swaminarayan temple, Bhuj",
    location: "Bhuj, Gujarat, India",
    review: "5 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 8,
    img: "",
    name: "BAPS Swaminarayan Temple, Jamnagar",
    location: "Bhuj, Gujarat, India",
    review: "3 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 9,
    img: "",
    name: "Swaminarayan Akshardham Gujarat",
    location: "Bhuj, Gujarat, India",
    review: "3 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 10,
    img: "",
    name: "Swaminarayan temple, Bhuj",
    location: "Bhuj, Gujarat, India",
    review: "4 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 11,
    img: "",
    name: "BAPS Swaminarayan Temple, Jamnagar",
    location: "Bhuj, Gujarat, India",
    review: "3 Reviews",
    price: "from ₹699,00/night",
  },
  {
    id: 12,
    img: "",
    name: "Swaminarayan Akshardham Gujarat",
    location: "Bhuj, Gujarat, India",
    review: "4 Reviews",
    price: "from ₹699,00/night",
  },
  // {
  //   id: 13,
  //   img: "",
  //   name: "Swaminarayan temple, Bhuj",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 14,
  //   img: "",
  //   name: "BAPS Swaminarayan Temple, Jamnagar",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 15,
  //   img: "",
  //   name: "Swaminarayan Akshardham Gujarat",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 16,
  //   img: "",
  //   name: "Swaminarayan temple, Bhuj",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 17,
  //   img: "",
  //   name: "BAPS Swaminarayan Temple, Jamnagar",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 18,
  //   img: "",
  //   name: "Swaminarayan Akshardham Gujarat",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 19,
  //   img: "",
  //   name: "Swaminarayan temple, Bhuj",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 20,
  //   img: "",
  //   name: "BAPS Swaminarayan Temple, Jamnagar",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 21,
  //   img: "",
  //   name: "Swaminarayan Akshardham Gujarat",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
  // {
  //   id: 22,
  //   img: "",
  //   name: "Swaminarayan Akshardham Gujarat",
  //   location: "Bhuj, Gujarat, India",
  //   review: "3.5 /5 Very Good • 3 Reviews",
  //   price: "from ₹699,00/night",
  // },
];

export default Temple;
